### ISSUE TITLE
Not working in Ubuntu 20.04/Python3 - ARM (Rock64)

### ISSUE THREAD

**Issue by gusarg81** [TaylorSMarks/playsound#64]
Hi, creating a simple test:

> Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from playsound import playsound
> >>> playsound('/home/rock64/file_example_MP3_700KB.mp3')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.8/dist-packages/playsound.py", line 101, in _playsoundNix
>     playbin.props.uri = 'file://' + pathname2url(os.path.abspath(sound))
> AttributeError: 'NoneType' object has no attribute 'props'

This error brings me here since I found problems in Open Assistant which uses this module to play sounds. So, I made that simple test which is the error that arises.

Any ideas?

**Comment by Legion-God** [comment]
I am using the Ubuntu 20.04/Python3.8.5 and it works fine, although I don't know much but judging from the traceback, I guess it has something to do with your filename instead of playsound itself. Try another file or renaming the current file.

**Comment by gusarg81** [comment]
Hi,

I've tried with different files, and with 2 machines with Ubuntu 20.04 and python 3.8.5. I found/discovered this bug when trying to use Open Assistant, which uses playsound a dependency. That is why I've ended up here.

**Comment by TaylorSMarks** [comment]
It might be a good idea to look at the list of commits and see who actually wrote the current Linux function and ask them to look into it.

I accepted their merge years ago without checking it because I don’t actually have any Linux machines with speakers connected to test with. Apparently it works for some people, though ¯\_(ツ)_/¯

**Comment by Legion-God** [comment]
> Hi,
> 
> I've tried with different files, and with 2 machines with Ubuntu 20.04 and python 3.8.5. I found/discovered this bug when trying to use Open Assistant, which uses playsound a dependency. That is why I've ended up here.

So for another machine, was the traceback same?

**Comment by gusarg81** [comment]
Yes, exactly the same.

**Comment by Legion-God** [comment]
I think the problem maybe with **gi**. So try doing this,
`pip install vext`
`pip install vext.gi`
maybe that will fix it?

**Comment by gusarg81** [comment]
Installing vext.gi:

>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-install-qatotoxb/vext.gi/setup.py", line 62, in <module>
>       setup(
>     File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
>       return distutils.core.setup(**attrs)
>     File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
>       self.run_command(cmd)
>     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 275, in run
>       self.egg2dist(self.egginfo_dir, distinfo_dir)
>     File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 372, in egg2dist
>       raise ValueError(err)
>   ValueError: Egg metadata expected at build/bdist.linux-aarch64/wheel/vext.gi-0.7.4.egg-info but not found
>   ----------------------------------------
>   ERROR: Failed building wheel for vext.gi

**Comment by gusarg81** [comment]
Just in case, I am using arm hardware (running Ubuntu 20.04).

**Comment by Legion-God** [comment]
Ok, I am running out of ideas, but you can try to install **gi** using Ubuntu's packet manager.
Try running `sudo apt install python3-gi`

**Comment by gusarg81** [comment]
Ok, now installed all inside venv and now error this time with vext.gi, but I have the same problem originally reported here. So, is not because vext/vext.gi.

**Comment by Legion-God** [comment]
I know this may sound really dumb, but have you tried, remote audio files. Does it work if the file is hosted online ?

**Comment by gusarg81** [comment]
Same result:
```
python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from playsound import playsound
>>> playsound('https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rock64/Apps/OpenAssistant/venv/lib/python3.8/site-packages/playsound.py", line 99, in _playsoundNix
    playbin.props.uri = sound
AttributeError: 'NoneType' object has no attribute 'props'
>>> 
```

**Comment by Legion-God** [comment]
Man, I feel dumb now. I was just playing remote files because I happen to work on a project that involves remote files and those work fine. But when I try to play my local files. I get a exception. 


> >>> playsound('file:///home/god/Music/L_theme.mp3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/god/Projects/dev-radio/venv/lib/python3.8/site-packages/playsound.py", line 105, in _playsoundNix
    raise PlaysoundException(
playsound.PlaysoundException: playbin.set_state returned <enum GST_STATE_CHANGE_FAILURE of type Gst.StateChangeReturn>

**Comment by Legion-God** [comment]
> Same result:
> 
> ```
> python3
> Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from playsound import playsound
> >>> playsound('https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/rock64/Apps/OpenAssistant/venv/lib/python3.8/site-packages/playsound.py", line 99, in _playsoundNix
>     playbin.props.uri = sound
> AttributeError: 'NoneType' object has no attribute 'props'
> >>> 
> ```

That file is playing for me tho.

**Comment by gusarg81** [comment]
> Man, I feel dumb now. I was just playing remote files because I happen to work on a project that involves remote files and those work fine. But when I try to play my local files. I get a exception.
> 
> > > > > playsound('file:///home/god/Music/L_theme.mp3')
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in 
> > > > > File "/home/god/Projects/dev-radio/venv/lib/python3.8/site-packages/playsound.py", line 105, in _playsoundNix
> > > > > raise PlaysoundException(
> > > > > playsound.PlaysoundException: playbin.set_state returned

Seems a different bug entirely. So it seems there is a problem with ARM platform? Maybe related to GStreamer in ARM platform? Just guessing here.

Also have in mind that this is a headless installation, does not have desktop at all (just in case).

**Comment by Legion-God** [comment]
Yup, I think too something is wrong with `Gst.ElementFactory.make()` in your case. I can't help with that. Sorry.

**Comment by gusarg81** [comment]
But anyway I help to debug? Is a shame, because for example apps like Open Assistant is being used a lot in SBC boards...

**Comment by Legion-God** [comment]
In my case, I don't require local files I am mostly dealing with streaming, so it would be fine.
I guess owner was right, you would have to contact the guy who made the PR for Linux Support.

**Comment by gusarg81** [comment]
Ok, installed almost every plugin from gstreamer1.0 packages and now the bug is gone. I wonder which one was the necessary dependency.

**Comment by Legion-God** [comment]
Well you could always find out, by removing plugins one by one, until the stuff breaks.

**Comment by BenjaminMickler** [comment]
I had the same issue. The packages that I needed were:
- gstreamer1.0-alsa
- gstreamer1.0-plugins-base
- gstreamer1.0-plugins-good
